name: Build and deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'frontend-e0e4fzaefvera4ct'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_57DE6218EA06497A9AFC06DE5F00FA59 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FBCA947AEDC14131BFF47957C6F757D9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ACFC626B9FA741C4ACAC7C4D643C6E3B }}

      - name: Prepare Frontend Artifact
        run: |
          # Заходим в папку фронтенда и зипуем только её содержимое в корень архива
          cd frontend
          zip -r ../frontend_only.zip . 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: frontend_only.zip