name: Deploy frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip frontend
        run: zip -r frontend.zip frontend

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: functions-app01   # ← если это frontend app поменяй имя
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: frontend.zip