name: Inventory Project CI

# Когда запускать робота?
on:
  push:
    branches: [ "main", "feature-inventory-update" ] # запускать при пуше в эти ветки
  pull_request:
    branches: [ "main" ] # и при создании пулл-реквестов

jobs:
  build:
    # На каком компьютере запускать (виртуальная машина Linux)
    runs-on: ubuntu-latest

    steps:
    # 1. Копируем код из репозитория на виртуальную машину
    - uses: actions/checkout@v4

    # 2. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Запускаем твои тесты
    - name: Run Tests
      run: |
        python -m unittest test_logic.py