name: Deploy frontend to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip frontend
        run: zip -r frontend.zip frontend/*

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D0A6850D8B349D6BCEA37829429B463 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5B8DF26EE6A844C3BA4DF4F8C7654A58 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1333DD72C268454F89116560C1B8ADBE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend'
          package: frontend.zip